;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		sp--cua-replace-region
		sp--self-insert-command
		suspend-frame
		upcase-region
		))

(setq mc/cmds-to-run-once
      '(
		mac-mwheel-scroll
		))
